### PR TITLE
Update cache management

### PR DESCRIPTION
**Pull request by MonsieurMan**
Move cache management in the same function to make it clearer.
Correctly handle undefined type guard when getting from cache.

### CODE REVIEW

**Comment by TristanFAURE** [comment]
still errors : https://circleci.com/gh/palantir/tslint/6105?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

did you run the test and the lint locally ?

**Comment by MonsieurMan** [comment]
I'm really sorry for the time you've lost on this, first time I did not run
the tests and second not the lint. I thought tests were running them too..
It should be good to go now! 🙂

Le mar. 3 juil. 2018 à 11:22 AM, Tristan FAURE <notifications@github.com> a
écrit :

**Comment by TristanFAURE** [comment]
Don't worry i didn't lose time on it, thank you for your contribution. I hope it will motivate the contributors to accept the PR 

**edit :** it seems it is ok, there are still issues for nextCi and the tests failed on other code than ours

**Comment by MonsieurMan** [comment]
Yes I hope it'll help get a little bit of thrust for this rule. It is necessary imo, enforce writing down real unit functions.
I have no clue what this test is about...

**Pull request merged**
